# Generated by Django 5.1.5 on 2026-02-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_add_bacteremia_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="resolution_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Recommendation Accepted"),
                    ("already_addressed", "Already Addressed"),
                    ("clinically_inappropriate", "Clinically Inappropriate"),
                    ("patient_discharged", "Patient Discharged"),
                    ("patient_expired", "Patient Expired"),
                    ("false_positive", "False Positive"),
                    ("duplicate", "Duplicate Alert"),
                    ("auto_resolved", "Auto-Resolved"),
                    ("messaged_team", "Messaged Team"),
                    ("discussed_with_team", "Discussed with Team"),
                    ("therapy_changed", "Therapy Changed"),
                    ("therapy_stopped", "Therapy Stopped"),
                    ("suggested_alternative", "Suggested Alternative"),
                    ("culture_pending", "Culture Pending"),
                    ("dose_adjusted", "Dose Adjusted"),
                    ("interval_adjusted", "Interval Adjusted"),
                    ("route_changed", "Route Changed"),
                    ("clinical_justification", "Clinical Justification"),
                    ("escalated_to_attending", "Escalated to Attending"),
                    ("no_action_needed", "No Action Needed"),
                    ("other", "Other Reason"),
                ],
                help_text="Reason for resolution",
                max_length=50,
                null=True,
            ),
        ),
    ]
