# Generated by Django 5.1.5 on 2026-02-09 01:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitorState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "monitor_type",
                    models.CharField(
                        help_text="Monitor type: trigger / episode / adherence",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "last_poll_time",
                    models.DateTimeField(
                        blank=True, help_text="When this monitor last polled", null=True
                    ),
                ),
                (
                    "last_run_status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="success / error",
                        max_length=50,
                    ),
                ),
                (
                    "state_data",
                    models.JSONField(default=dict, help_text="Extra checkpoint data"),
                ),
            ],
            options={
                "verbose_name": "Monitor State",
                "verbose_name_plural": "Monitor States",
                "db_table": "guideline_monitor_state",
            },
        ),
        migrations.CreateModel(
            name="BundleEpisode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        db_index=True,
                        help_text="FHIR Patient resource ID",
                        max_length=255,
                    ),
                ),
                (
                    "patient_mrn",
                    models.CharField(
                        db_index=True, help_text="Medical Record Number", max_length=100
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Patient name (display only)",
                        max_length=255,
                    ),
                ),
                (
                    "encounter_id",
                    models.CharField(
                        help_text="FHIR Encounter resource ID", max_length=255
                    ),
                ),
                (
                    "bundle_id",
                    models.CharField(
                        db_index=True,
                        help_text="Bundle identifier (e.g., sepsis_peds_2024)",
                        max_length=100,
                    ),
                ),
                (
                    "bundle_name",
                    models.CharField(
                        help_text="Human-readable bundle name", max_length=255
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        help_text="What triggered this episode (diagnosis, order, lab)",
                        max_length=50,
                    ),
                ),
                (
                    "trigger_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ICD-10, LOINC, or CPT code that triggered",
                        max_length=100,
                    ),
                ),
                (
                    "trigger_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Description of trigger event",
                        max_length=500,
                    ),
                ),
                (
                    "trigger_time",
                    models.DateTimeField(help_text="When the bundle was triggered"),
                ),
                (
                    "patient_age_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Patient age in days at trigger time",
                        null=True,
                    ),
                ),
                (
                    "patient_age_months",
                    models.FloatField(
                        blank=True,
                        help_text="Patient age in months at trigger time",
                        null=True,
                    ),
                ),
                (
                    "patient_unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hospital unit at trigger time",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("complete", "Complete"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current episode status",
                        max_length=20,
                    ),
                ),
                (
                    "adherence_percentage",
                    models.FloatField(
                        default=0,
                        help_text="Percentage of applicable elements met (0-100)",
                    ),
                ),
                (
                    "adherence_level",
                    models.CharField(
                        choices=[
                            ("full", "Full Adherence"),
                            ("partial", "Partial Adherence"),
                            ("low", "Low Adherence"),
                            ("na", "Not Applicable"),
                        ],
                        default="na",
                        help_text="Adherence level classification",
                        max_length=20,
                    ),
                ),
                ("elements_total", models.IntegerField(default=0)),
                ("elements_applicable", models.IntegerField(default=0)),
                ("elements_met", models.IntegerField(default=0)),
                ("elements_not_met", models.IntegerField(default=0)),
                ("elements_pending", models.IntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="pending_review / reviewed / not_applicable",
                        max_length=50,
                    ),
                ),
                (
                    "overall_determination",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Final determination from review",
                        max_length=100,
                    ),
                ),
                (
                    "clinical_context",
                    models.JSONField(
                        default=dict,
                        help_text="NLP assessment data (appearance, evidence)",
                    ),
                ),
                (
                    "last_assessment_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When last LLM assessment was run",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When episode was completed/closed",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bundle Episode",
                "verbose_name_plural": "Bundle Episodes",
                "db_table": "guideline_episodes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["bundle_id", "status"],
                        name="guideline_e_bundle__671930_idx",
                    ),
                    models.Index(
                        fields=["patient_mrn", "status"],
                        name="guideline_e_patient_be59b6_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="guideline_e_status_4ec49c_idx",
                    ),
                ],
                "unique_together": {
                    ("patient_id", "encounter_id", "bundle_id", "trigger_time")
                },
            },
        ),
        migrations.CreateModel(
            name="EpisodeAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        help_text="Type of assessment (clinical_impression, gi_symptoms)",
                        max_length=100,
                    ),
                ),
                (
                    "primary_determination",
                    models.CharField(
                        help_text="guideline_appropriate / guideline_deviation / pending",
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(help_text="high / medium / low", max_length=20),
                ),
                (
                    "reasoning",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="LLM reasoning for determination",
                    ),
                ),
                (
                    "supporting_evidence",
                    models.JSONField(default=list, help_text="List of evidence items"),
                ),
                (
                    "extraction_data",
                    models.JSONField(
                        default=dict,
                        help_text="Raw extraction data (concerning_signs, reassuring_signs, appearance)",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(help_text="LLM model identifier", max_length=100),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="LLM response time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="guideline_adherence.bundleepisode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode Assessment",
                "verbose_name_plural": "Episode Assessments",
                "db_table": "guideline_assessments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EpisodeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "reviewer",
                    models.CharField(
                        help_text="Reviewer name/username", max_length=255
                    ),
                ),
                (
                    "reviewer_decision",
                    models.CharField(
                        choices=[
                            ("guideline_appropriate", "Guideline Appropriate"),
                            ("guideline_deviation", "Guideline Deviation"),
                            ("needs_more_info", "Needs More Info"),
                        ],
                        help_text="Reviewer's determination",
                        max_length=50,
                    ),
                ),
                (
                    "llm_decision",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What the LLM determined (for comparison)",
                        max_length=50,
                    ),
                ),
                (
                    "is_override",
                    models.BooleanField(
                        default=False,
                        help_text="Whether reviewer overrode the LLM determination",
                    ),
                ),
                (
                    "override_reason_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Category: extraction_error / element_detection_error / clinical_judgment / etc.",
                        max_length=100,
                    ),
                ),
                (
                    "deviation_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="documentation / timing / missing_element / clinical_judgment",
                        max_length=100,
                    ),
                ),
                (
                    "extraction_corrections",
                    models.JSONField(
                        default=dict, help_text="Corrections to LLM extraction"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Reviewer notes"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the review was submitted"
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assessment being reviewed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="guideline_adherence.episodeassessment",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="guideline_adherence.bundleepisode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode Review",
                "verbose_name_plural": "Episode Reviews",
                "db_table": "guideline_reviews",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="ElementResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "element_id",
                    models.CharField(
                        help_text="Element identifier (e.g., sepsis_blood_cx)",
                        max_length=100,
                    ),
                ),
                (
                    "element_name",
                    models.CharField(
                        help_text="Human-readable element name", max_length=255
                    ),
                ),
                (
                    "element_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Description of the element requirement",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("met", "Met"),
                            ("not_met", "Not Met"),
                            ("pending", "Pending"),
                            ("na", "Not Applicable"),
                            ("unable", "Unable to Assess"),
                        ],
                        default="pending",
                        help_text="Current check status",
                        max_length=20,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this element is required for this patient",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What was found (lab value, medication name, etc.)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Notes about the check result"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this element must be completed by",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the element was completed",
                        null=True,
                    ),
                ),
                (
                    "time_window_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Time window in hours from trigger",
                        null=True,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="element_results",
                        to="guideline_adherence.bundleepisode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Element Result",
                "verbose_name_plural": "Element Results",
                "db_table": "guideline_element_results",
                "ordering": ["element_id"],
                "unique_together": {("episode", "element_id")},
            },
        ),
    ]
