# Generated by Django 5.1.5 on 2026-02-08 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MDROCase",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        db_index=True,
                        help_text="FHIR Patient resource ID",
                        max_length=255,
                    ),
                ),
                (
                    "patient_mrn",
                    models.CharField(
                        db_index=True, help_text="Medical Record Number", max_length=100
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Patient full name",
                        max_length=255,
                    ),
                ),
                (
                    "culture_id",
                    models.CharField(
                        help_text="FHIR DiagnosticReport ID (deduplication key)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "culture_date",
                    models.DateTimeField(
                        db_index=True, help_text="Date/time culture was collected"
                    ),
                ),
                (
                    "specimen_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Specimen type (Blood, Urine, Respiratory, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "organism",
                    models.CharField(
                        help_text="Organism identified in culture", max_length=255
                    ),
                ),
                (
                    "mdro_type",
                    models.CharField(
                        choices=[
                            ("mrsa", "MRSA"),
                            ("vre", "VRE"),
                            ("cre", "CRE"),
                            ("esbl", "ESBL"),
                            ("crpa", "CRPA"),
                            ("crab", "CRAB"),
                        ],
                        db_index=True,
                        help_text="Type of MDRO",
                        max_length=10,
                    ),
                ),
                (
                    "resistant_antibiotics",
                    models.JSONField(
                        default=list,
                        help_text="List of antibiotics the organism is resistant to",
                    ),
                ),
                (
                    "susceptibilities",
                    models.JSONField(
                        default=list,
                        help_text="Full susceptibility results [{antibiotic, result, mic}]",
                    ),
                ),
                (
                    "classification_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason for MDRO classification",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Facility name",
                        max_length=255,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Hospital unit",
                        max_length=100,
                    ),
                ),
                (
                    "admission_date",
                    models.DateTimeField(
                        blank=True, help_text="Patient admission date", null=True
                    ),
                ),
                (
                    "days_since_admission",
                    models.IntegerField(
                        blank=True,
                        help_text="Days between admission and culture collection",
                        null=True,
                    ),
                ),
                (
                    "transmission_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("community", "Community Onset"),
                            ("healthcare", "Healthcare Onset"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Community vs healthcare onset",
                        max_length=20,
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(
                        default=True,
                        help_text="First isolation of this MDRO type for this patient",
                    ),
                ),
                (
                    "prior_history",
                    models.BooleanField(
                        default=False, help_text="Patient has prior MDRO history"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the case was reviewed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Review notes"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed the case",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_mdro_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MDRO Case",
                "verbose_name_plural": "MDRO Cases",
                "db_table": "mdro_cases",
                "ordering": ["-culture_date"],
            },
        ),
        migrations.CreateModel(
            name="MDROProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "culture_id",
                    models.CharField(
                        help_text="FHIR DiagnosticReport ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the culture was processed"
                    ),
                ),
                (
                    "is_mdro",
                    models.BooleanField(
                        help_text="Whether the culture was classified as MDRO"
                    ),
                ),
                (
                    "mdro_type",
                    models.CharField(
                        blank=True,
                        help_text="MDRO type if classified as MDRO",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        help_text="Created MDRO case (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_logs",
                        to="mdro.mdrocase",
                    ),
                ),
            ],
            options={
                "verbose_name": "MDRO Processing Log",
                "verbose_name_plural": "MDRO Processing Logs",
                "db_table": "mdro_processing_log",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="MDROReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "reviewer",
                    models.CharField(help_text="Name of the reviewer", max_length=255),
                ),
                (
                    "decision",
                    models.CharField(
                        help_text="Review decision (confirmed, rejected, needs_info)",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Review notes"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="MDRO case being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="mdro.mdrocase",
                    ),
                ),
            ],
            options={
                "verbose_name": "MDRO Review",
                "verbose_name_plural": "MDRO Reviews",
                "db_table": "mdro_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mdrocase",
            index=models.Index(
                fields=["patient_mrn", "mdro_type"],
                name="mdro_cases_patient_1e5dfd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mdrocase",
            index=models.Index(
                fields=["mdro_type", "-culture_date"],
                name="mdro_cases_mdro_ty_ecf110_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mdrocase",
            index=models.Index(
                fields=["unit", "-culture_date"], name="mdro_cases_unit_1ddb16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mdrocase",
            index=models.Index(
                fields=["transmission_status", "-culture_date"],
                name="mdro_cases_transmi_f972e1_idx",
            ),
        ),
    ]
