# Generated by Django 5.1.5 on 2026-02-09 01:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0004_alter_alert_alert_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("procedure_category", models.CharField(blank=True, max_length=30)),
                ("surgeon_id", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("total_cases", models.IntegerField(default=0)),
                ("excluded_cases", models.IntegerField(default=0)),
                ("bundle_compliant_count", models.IntegerField(default=0)),
                ("bundle_compliance_rate", models.FloatField(default=0.0)),
                ("indication_rate", models.FloatField(default=0.0)),
                ("agent_rate", models.FloatField(default=0.0)),
                ("timing_rate", models.FloatField(default=0.0)),
                ("dosing_rate", models.FloatField(default=0.0)),
                ("redosing_rate", models.FloatField(default=0.0)),
                ("postop_rate", models.FloatField(default=0.0)),
                ("discontinuation_rate", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Compliance Metric",
                "verbose_name_plural": "Compliance Metrics",
                "db_table": "prophylaxis_compliance_metrics",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="SurgicalCase",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "case_id",
                    models.CharField(
                        help_text="FHIR Procedure ID or external case identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("patient_mrn", models.CharField(db_index=True, max_length=100)),
                ("patient_name", models.CharField(blank=True, max_length=255)),
                ("encounter_id", models.CharField(blank=True, max_length=100)),
                (
                    "cpt_codes",
                    models.JSONField(
                        default=list, help_text="List of CPT code strings"
                    ),
                ),
                ("procedure_description", models.CharField(max_length=500)),
                (
                    "procedure_category",
                    models.CharField(
                        choices=[
                            ("cardiac", "Cardiac"),
                            ("thoracic", "Thoracic"),
                            ("gastrointestinal_upper", "GI Upper"),
                            ("gastrointestinal_colorectal", "GI Colorectal"),
                            ("hepatobiliary", "Hepatobiliary"),
                            ("orthopedic", "Orthopedic"),
                            ("neurosurgery", "Neurosurgery"),
                            ("urology", "Urology"),
                            ("ent", "ENT"),
                            ("hernia", "Hernia"),
                            ("plastics", "Plastics"),
                            ("vascular", "Vascular"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("surgeon_id", models.CharField(blank=True, max_length=100)),
                ("surgeon_name", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("scheduled_or_time", models.DateTimeField(blank=True, null=True)),
                ("actual_incision_time", models.DateTimeField(blank=True, null=True)),
                ("surgery_end_time", models.DateTimeField(blank=True, null=True)),
                ("patient_weight_kg", models.FloatField(blank=True, null=True)),
                ("patient_age_years", models.FloatField(blank=True, null=True)),
                ("allergies", models.JSONField(default=list)),
                ("has_beta_lactam_allergy", models.BooleanField(default=False)),
                ("mrsa_colonized", models.BooleanField(default=False)),
                ("is_emergency", models.BooleanField(default=False)),
                ("already_on_therapeutic_abx", models.BooleanField(default=False)),
                ("documented_infection", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Surgical Case",
                "verbose_name_plural": "Surgical Cases",
                "db_table": "surgical_cases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient_mrn"], name="surgical_ca_patient_18c371_idx"
                    ),
                    models.Index(
                        fields=["encounter_id"], name="surgical_ca_encount_16b8ab_idx"
                    ),
                    models.Index(
                        fields=["scheduled_or_time"],
                        name="surgical_ca_schedul_85d0c7_idx",
                    ),
                    models.Index(
                        fields=["procedure_category"],
                        name="surgical_ca_procedu_b0978f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProphylaxisMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "medication_type",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("administration", "Administration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("medication_name", models.CharField(max_length=255)),
                ("dose_mg", models.FloatField()),
                ("route", models.CharField(default="IV", max_length=50)),
                (
                    "event_time",
                    models.DateTimeField(help_text="Order time or administration time"),
                ),
                ("frequency", models.CharField(blank=True, max_length=50)),
                ("duration_hours", models.FloatField(blank=True, null=True)),
                ("infusion_end_time", models.DateTimeField(blank=True, null=True)),
                ("order_id", models.CharField(blank=True, max_length=255)),
                (
                    "fhir_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="surgical_prophylaxis.surgicalcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prophylaxis Medication",
                "verbose_name_plural": "Prophylaxis Medications",
                "db_table": "prophylaxis_medications",
                "ordering": ["event_time"],
            },
        ),
        migrations.CreateModel(
            name="ProphylaxisEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "evaluation_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("indication_result", models.JSONField(default=dict)),
                ("agent_result", models.JSONField(default=dict)),
                ("timing_result", models.JSONField(default=dict)),
                ("dosing_result", models.JSONField(default=dict)),
                ("redosing_result", models.JSONField(default=dict)),
                ("postop_result", models.JSONField(default=dict)),
                ("discontinuation_result", models.JSONField(default=dict)),
                ("bundle_compliant", models.BooleanField(default=False)),
                ("compliance_score", models.FloatField(default=0.0)),
                ("elements_met", models.IntegerField(default=0)),
                ("elements_total", models.IntegerField(default=0)),
                ("flags", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("excluded", models.BooleanField(default=False)),
                ("exclusion_reason", models.CharField(blank=True, max_length=255)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prophylaxis_evaluations",
                        to="alerts.alert",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="surgical_prophylaxis.surgicalcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prophylaxis Evaluation",
                "verbose_name_plural": "Prophylaxis Evaluations",
                "db_table": "prophylaxis_evaluations",
                "ordering": ["-evaluation_time"],
            },
        ),
        migrations.CreateModel(
            name="SurgicalJourney",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("journey_id", models.CharField(max_length=50, unique=True)),
                ("patient_mrn", models.CharField(db_index=True, max_length=100)),
                ("patient_name", models.CharField(blank=True, max_length=255)),
                ("procedure_description", models.CharField(blank=True, max_length=500)),
                ("procedure_cpt_codes", models.JSONField(default=list)),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("inpatient", "Inpatient"),
                            ("pre_op", "Pre-Op Holding"),
                            ("or_suite", "OR Suite"),
                            ("pacu", "PACU"),
                            ("discharged", "Discharged"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("prophylaxis_indicated", models.BooleanField(blank=True, null=True)),
                ("order_exists", models.BooleanField(default=False)),
                ("administered", models.BooleanField(default=False)),
                ("alert_t24_sent", models.BooleanField(default=False)),
                ("alert_t24_time", models.DateTimeField(blank=True, null=True)),
                ("alert_t2_sent", models.BooleanField(default=False)),
                ("alert_t2_time", models.DateTimeField(blank=True, null=True)),
                ("alert_t60_sent", models.BooleanField(default=False)),
                ("alert_t60_time", models.DateTimeField(blank=True, null=True)),
                ("alert_t0_sent", models.BooleanField(default=False)),
                ("alert_t0_time", models.DateTimeField(blank=True, null=True)),
                ("is_emergency", models.BooleanField(default=False)),
                ("already_on_therapeutic_abx", models.BooleanField(default=False)),
                ("excluded", models.BooleanField(default=False)),
                ("exclusion_reason", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("fhir_appointment_id", models.CharField(blank=True, max_length=255)),
                ("fhir_encounter_id", models.CharField(blank=True, max_length=255)),
                ("hl7_visit_number", models.CharField(blank=True, max_length=100)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journeys",
                        to="surgical_prophylaxis.surgicalcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Surgical Journey",
                "verbose_name_plural": "Surgical Journeys",
                "db_table": "surgical_journeys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreOpCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("t24", "T-24h"),
                            ("t2", "T-2h"),
                            ("t60", "T-60min"),
                            ("t0", "T-0 (OR Entry)"),
                            ("preop_arrival", "Pre-Op Arrival"),
                            ("or_entry", "OR Entry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trigger_time", models.DateTimeField()),
                ("prophylaxis_indicated", models.BooleanField(default=False)),
                ("order_exists", models.BooleanField(default=False)),
                ("administered", models.BooleanField(default=False)),
                ("minutes_to_or", models.IntegerField(blank=True, null=True)),
                ("alert_required", models.BooleanField(default=False)),
                ("alert_severity", models.CharField(blank=True, max_length=20)),
                ("recommendation", models.TextField(blank=True)),
                ("check_details", models.JSONField(default=dict)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preop_checks",
                        to="alerts.alert",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="surgical_prophylaxis.surgicaljourney",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Op Check",
                "verbose_name_plural": "Pre-Op Checks",
                "db_table": "preop_checks",
                "ordering": ["-trigger_time"],
            },
        ),
        migrations.CreateModel(
            name="PatientLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("patient_mrn", models.CharField(db_index=True, max_length=100)),
                ("location_code", models.CharField(max_length=100)),
                (
                    "location_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("inpatient", "Inpatient"),
                            ("pre_op", "Pre-Op Holding"),
                            ("or_suite", "OR Suite"),
                            ("pacu", "PACU"),
                            ("discharged", "Discharged"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("message_time", models.DateTimeField(blank=True, null=True)),
                ("hl7_message_id", models.CharField(blank=True, max_length=255)),
                (
                    "journey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="surgical_prophylaxis.surgicaljourney",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Location",
                "verbose_name_plural": "Patient Locations",
                "db_table": "patient_locations",
                "ordering": ["-event_time"],
            },
        ),
        migrations.CreateModel(
            name="AlertEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "alert_ref",
                    models.CharField(
                        help_text="Reference to Alert UUID", max_length=255
                    ),
                ),
                ("escalation_level", models.IntegerField(default=1)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("t24", "T-24h"),
                            ("t2", "T-2h"),
                            ("t60", "T-60min"),
                            ("t0", "T-0 (OR Entry)"),
                            ("preop_arrival", "Pre-Op Arrival"),
                            ("or_entry", "OR Entry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_role", models.CharField(max_length=50)),
                ("recipient_id", models.CharField(blank=True, max_length=255)),
                ("recipient_name", models.CharField(blank=True, max_length=255)),
                ("delivery_channel", models.CharField(max_length=50)),
                ("sent_at", models.DateTimeField()),
                ("delivery_status", models.CharField(default="pending", max_length=20)),
                ("response_at", models.DateTimeField(blank=True, null=True)),
                ("response_action", models.CharField(blank=True, max_length=100)),
                ("response_by", models.CharField(blank=True, max_length=255)),
                ("next_escalation_at", models.DateTimeField(blank=True, null=True)),
                ("escalated", models.BooleanField(default=False)),
                (
                    "journey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations",
                        to="surgical_prophylaxis.surgicaljourney",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Escalation",
                "verbose_name_plural": "Alert Escalations",
                "db_table": "alert_escalations",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="surgicaljourney",
            index=models.Index(
                fields=["patient_mrn"], name="surgical_jo_patient_8f949e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surgicaljourney",
            index=models.Index(
                fields=["current_state"], name="surgical_jo_current_dada67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surgicaljourney",
            index=models.Index(
                fields=["scheduled_time"], name="surgical_jo_schedul_63d8f6_idx"
            ),
        ),
    ]
