# Generated by Django 5.1.5 on 2026-02-09 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hai_detection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AUPatientLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("patient_id", models.CharField(max_length=255)),
                ("patient_mrn", models.CharField(max_length=100)),
                ("encounter_id", models.CharField(max_length=255)),
                ("antimicrobial_code", models.CharField(max_length=50)),
                ("antimicrobial_name", models.CharField(max_length=255)),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("IV", "IV"),
                            ("PO", "PO"),
                            ("IM", "IM"),
                            ("TOPICAL", "Topical"),
                            ("INHALED", "Inhaled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("total_doses", models.IntegerField(default=0)),
                ("days_of_therapy", models.FloatField(default=0)),
                (
                    "location_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "indication",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "db_table": "nhsn_au_patient_level",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("submission_type", models.CharField(max_length=20)),
                ("reporting_period", models.CharField(max_length=20)),
                ("user", models.CharField(max_length=255)),
                ("event_count", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "nhsn_submission_audit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ARQuarterlySummary",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reporting_quarter", models.CharField(max_length=7)),
                ("location_code", models.CharField(max_length=50)),
                (
                    "location_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "nhsn_ar_quarterly",
                "ordering": ["-reporting_quarter", "location_code"],
                "unique_together": {("reporting_quarter", "location_code")},
            },
        ),
        migrations.CreateModel(
            name="ARPhenotypeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("organism_code", models.CharField(max_length=100)),
                ("organism_name", models.CharField(max_length=255)),
                (
                    "phenotype",
                    models.CharField(
                        choices=[
                            ("MRSA", "Methicillin-resistant S. aureus"),
                            ("MSSA", "Methicillin-susceptible S. aureus"),
                            ("VRE", "Vancomycin-resistant Enterococcus"),
                            ("VSE", "Vancomycin-susceptible Enterococcus"),
                            ("ESBL", "Extended-spectrum beta-lactamase"),
                            ("CRE", "Carbapenem-resistant Enterobacterales"),
                            ("CRPA", "Carbapenem-resistant P. aeruginosa"),
                            ("CRAB", "Carbapenem-resistant A. baumannii"),
                            ("MDR", "Multi-drug resistant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_isolates", models.IntegerField(default=0)),
                ("resistant_isolates", models.IntegerField(default=0)),
                ("percent_resistant", models.FloatField(blank=True, null=True)),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phenotypes",
                        to="nhsn_reporting.arquarterlysummary",
                    ),
                ),
            ],
            options={
                "db_table": "nhsn_ar_phenotypes",
                "ordering": ["organism_name", "phenotype"],
            },
        ),
        migrations.CreateModel(
            name="ARIsolate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patient_id", models.CharField(max_length=255)),
                ("patient_mrn", models.CharField(max_length=100)),
                ("encounter_id", models.CharField(max_length=255)),
                ("specimen_date", models.DateField()),
                ("specimen_type", models.CharField(max_length=50)),
                ("organism_code", models.CharField(max_length=100)),
                ("organism_name", models.CharField(max_length=255)),
                (
                    "specimen_source",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "location_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("is_first_isolate", models.BooleanField(default=True)),
                ("is_hai_associated", models.BooleanField(default=False)),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isolates",
                        to="nhsn_reporting.arquarterlysummary",
                    ),
                ),
            ],
            options={
                "db_table": "nhsn_ar_isolates",
                "ordering": ["-specimen_date"],
            },
        ),
        migrations.CreateModel(
            name="ARSusceptibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("antimicrobial_code", models.CharField(max_length=50)),
                ("antimicrobial_name", models.CharField(max_length=255)),
                (
                    "interpretation",
                    models.CharField(
                        choices=[
                            ("S", "Susceptible"),
                            ("I", "Intermediate"),
                            ("R", "Resistant"),
                            ("NS", "Non-susceptible"),
                        ],
                        max_length=5,
                    ),
                ),
                ("mic_value", models.CharField(blank=True, default="", max_length=50)),
                ("mic_numeric", models.FloatField(blank=True, null=True)),
                ("disk_zone", models.FloatField(blank=True, null=True)),
                (
                    "testing_method",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "breakpoint_source",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "isolate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="susceptibilities",
                        to="nhsn_reporting.arisolate",
                    ),
                ),
            ],
            options={
                "db_table": "nhsn_ar_susceptibilities",
                "ordering": ["antimicrobial_name"],
            },
        ),
        migrations.CreateModel(
            name="AUMonthlySummary",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reporting_month", models.CharField(max_length=7)),
                ("location_code", models.CharField(max_length=50)),
                (
                    "location_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("patient_days", models.IntegerField(default=0)),
                ("admissions", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "nhsn_au_monthly",
                "ordering": ["-reporting_month", "location_code"],
                "unique_together": {("reporting_month", "location_code")},
            },
        ),
        migrations.CreateModel(
            name="AUAntimicrobialUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("antimicrobial_code", models.CharField(max_length=50)),
                ("antimicrobial_name", models.CharField(max_length=255)),
                (
                    "antimicrobial_class",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("IV", "IV"),
                            ("PO", "PO"),
                            ("IM", "IM"),
                            ("TOPICAL", "Topical"),
                            ("INHALED", "Inhaled"),
                        ],
                        default="IV",
                        max_length=20,
                    ),
                ),
                ("days_of_therapy", models.FloatField(default=0)),
                ("defined_daily_doses", models.FloatField(blank=True, null=True)),
                ("doses_administered", models.IntegerField(default=0)),
                ("patients_treated", models.IntegerField(default=0)),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="nhsn_reporting.aumonthlysummary",
                    ),
                ),
            ],
            options={
                "db_table": "nhsn_au_usage",
                "ordering": ["antimicrobial_class", "antimicrobial_name"],
            },
        ),
        migrations.CreateModel(
            name="DenominatorDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("date", models.DateField()),
                ("location_code", models.CharField(max_length=50)),
                (
                    "location_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("patient_days", models.IntegerField(default=0)),
                ("central_line_days", models.IntegerField(default=0)),
                ("urinary_catheter_days", models.IntegerField(default=0)),
                ("ventilator_days", models.IntegerField(default=0)),
                ("admissions", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "nhsn_denominators_daily",
                "ordering": ["-date", "location_code"],
                "unique_together": {("date", "location_code")},
            },
        ),
        migrations.CreateModel(
            name="DenominatorMonthly",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.CharField(max_length=7)),
                ("location_code", models.CharField(max_length=50)),
                (
                    "location_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("patient_days", models.IntegerField(default=0)),
                ("central_line_days", models.IntegerField(default=0)),
                ("urinary_catheter_days", models.IntegerField(default=0)),
                ("ventilator_days", models.IntegerField(default=0)),
                ("admissions", models.IntegerField(default=0)),
                ("central_line_utilization", models.FloatField(blank=True, null=True)),
                (
                    "urinary_catheter_utilization",
                    models.FloatField(blank=True, null=True),
                ),
                ("ventilator_utilization", models.FloatField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "nhsn_denominators_monthly",
                "ordering": ["-month", "location_code"],
                "unique_together": {("month", "location_code")},
            },
        ),
        migrations.CreateModel(
            name="NHSNEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "hai_type",
                    models.CharField(
                        choices=[
                            ("clabsi", "CLABSI"),
                            ("cauti", "CAUTI"),
                            ("ssi", "SSI"),
                            ("vae", "VAE"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "pathogen_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("reported", models.BooleanField(default=False)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nhsn_events",
                        to="hai_detection.haicandidate",
                    ),
                ),
            ],
            options={
                "db_table": "nhsn_events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.AddField(
            model_name="arisolate",
            name="hai_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="isolates",
                to="nhsn_reporting.nhsnevent",
            ),
        ),
    ]
