# Generated by Django 5.1.5 on 2026-02-08 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutbreakCluster",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "infection_type",
                    models.CharField(
                        db_index=True,
                        help_text="Infection type (e.g., mrsa, vre, clabsi, cdi)",
                        max_length=50,
                    ),
                ),
                (
                    "organism",
                    models.CharField(
                        blank=True,
                        help_text="Primary organism if applicable",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        db_index=True,
                        help_text="Hospital unit where cases occurred",
                        max_length=100,
                    ),
                ),
                (
                    "case_count",
                    models.IntegerField(
                        default=0, help_text="Number of cases in this cluster"
                    ),
                ),
                (
                    "first_case_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date of the first case in cluster",
                        null=True,
                    ),
                ),
                (
                    "last_case_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of the most recent case", null=True
                    ),
                ),
                (
                    "window_days",
                    models.IntegerField(
                        default=14, help_text="Time window in days for clustering"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("investigating", "Under Investigation"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("resolution_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Outbreak Cluster",
                "verbose_name_plural": "Outbreak Clusters",
                "db_table": "outbreak_clusters",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["infection_type", "unit", "status"],
                        name="outbreak_cl_infecti_e8066a_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="outbreak_cl_status_d79b95_idx",
                    ),
                    models.Index(
                        fields=["severity", "status"],
                        name="outbreak_cl_severit_8a23fc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClusterCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Data source: mdro, hai, or cdi", max_length=20
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="ID in the source system (MDROCase or HAICandidate UUID)",
                        max_length=255,
                    ),
                ),
                ("patient_id", models.CharField(max_length=255)),
                ("patient_mrn", models.CharField(max_length=100)),
                ("event_date", models.DateTimeField()),
                ("organism", models.CharField(blank=True, max_length=255, null=True)),
                ("infection_type", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=100)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="outbreak_detection.outbreakcluster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cluster Case",
                "verbose_name_plural": "Cluster Cases",
                "db_table": "outbreak_cluster_cases",
                "ordering": ["-event_date"],
                "indexes": [
                    models.Index(
                        fields=["cluster", "-event_date"],
                        name="outbreak_cl_cluster_7f3a3d_idx",
                    ),
                    models.Index(
                        fields=["source", "source_id"],
                        name="outbreak_cl_source_7aa93c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"),
                        name="unique_outbreak_source_case",
                    )
                ],
            },
        ),
    ]
