# Generated by Django 5.1.5 on 2026-02-09 00:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0004_alter_alert_alert_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicationCandidate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patient_id", models.CharField(db_index=True, max_length=255)),
                ("patient_mrn", models.CharField(db_index=True, max_length=100)),
                (
                    "patient_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "patient_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "medication_request_id",
                    models.CharField(
                        help_text="FHIR MedicationRequest ID (dedup key)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("medication_name", models.CharField(max_length=255)),
                (
                    "rxnorm_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("order_date", models.DateTimeField()),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("service", models.CharField(blank=True, default="", max_length=255)),
                (
                    "clinical_syndrome",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Taxonomy ID (e.g., 'cap', 'uti_simple')",
                        max_length=100,
                    ),
                ),
                (
                    "clinical_syndrome_display",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable syndrome name",
                        max_length=255,
                    ),
                ),
                (
                    "syndrome_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Category (respiratory, urinary, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "syndrome_confidence",
                    models.CharField(
                        choices=[
                            ("definite", "Definite"),
                            ("probable", "Probable"),
                            ("unclear", "Unclear"),
                        ],
                        default="unclear",
                        max_length=20,
                    ),
                ),
                (
                    "therapy_intent",
                    models.CharField(
                        choices=[
                            ("empiric", "Empiric"),
                            ("directed", "Directed"),
                            ("prophylaxis", "Prophylaxis"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "supporting_evidence",
                    models.JSONField(
                        blank=True, default=list, help_text="List of clinical findings"
                    ),
                ),
                (
                    "evidence_quotes",
                    models.JSONField(
                        blank=True, default=list, help_text="Direct quotes from notes"
                    ),
                ),
                (
                    "guideline_disease_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="CCHMC disease IDs from taxonomy mapping",
                    ),
                ),
                ("indication_not_documented", models.BooleanField(default=False)),
                ("likely_viral", models.BooleanField(default=False)),
                ("asymptomatic_bacteriuria", models.BooleanField(default=False)),
                ("never_appropriate", models.BooleanField(default=False)),
                (
                    "cchmc_disease_matched",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "cchmc_agent_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first_line", "First Line"),
                            ("alternative", "Alternative"),
                            ("off_guideline", "Off Guideline"),
                            ("not_assessed", "Not Assessed"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("cchmc_first_line_agents", models.JSONField(blank=True, null=True)),
                ("cchmc_recommendation", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("alerted", "Alert Created"),
                            ("reviewed", "Reviewed"),
                            ("auto_accepted", "Auto-Accepted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indication_candidates",
                        to="alerts.alert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indication Candidate",
                "verbose_name_plural": "Indication Candidates",
                "db_table": "abx_indication_candidates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IndicationLLMAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=200)),
                ("success", models.BooleanField()),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("response_time_ms", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to="abx_indications.indicationcandidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Audit Log Entry",
                "verbose_name_plural": "LLM Audit Log Entries",
                "db_table": "abx_indication_llm_audit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IndicationReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "syndrome_decision",
                    models.CharField(
                        choices=[
                            ("confirm_syndrome", "Confirm Syndrome"),
                            ("correct_syndrome", "Correct Syndrome"),
                            ("no_indication", "No Indication"),
                            ("viral_illness", "Viral Illness"),
                            ("asymptomatic_bacteriuria", "Asymptomatic Bacteriuria"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "confirmed_syndrome",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Corrected syndrome ID (if decision is correct_syndrome)",
                        max_length=100,
                    ),
                ),
                (
                    "confirmed_syndrome_display",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "agent_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("appropriate", "Appropriate"),
                            ("acceptable", "Acceptable"),
                            ("inappropriate", "Inappropriate"),
                            ("skip", "Skip"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("agent_notes", models.TextField(blank=True, default="")),
                ("is_override", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="abx_indications.indicationcandidate",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Indication Review",
                "verbose_name_plural": "Indication Reviews",
                "db_table": "abx_indication_reviews",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="indicationcandidate",
            index=models.Index(
                fields=["status", "-created_at"], name="abx_indicat_status_674b79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indicationcandidate",
            index=models.Index(
                fields=["patient_mrn", "-created_at"],
                name="abx_indicat_patient_940a41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="indicationcandidate",
            index=models.Index(
                fields=["medication_name", "-created_at"],
                name="abx_indicat_medicat_d2d2ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="indicationcandidate",
            index=models.Index(
                fields=["clinical_syndrome"], name="abx_indicat_clinica_1ac884_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indicationcandidate",
            index=models.Index(
                fields=["cchmc_agent_category"], name="abx_indicat_cchmc_a_82f0db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indicationllmauditlog",
            index=models.Index(
                fields=["candidate", "-created_at"],
                name="abx_indicat_candida_b58728_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="indicationllmauditlog",
            index=models.Index(fields=["model"], name="abx_indicat_model_071a22_idx"),
        ),
        migrations.AddIndex(
            model_name="indicationreview",
            index=models.Index(
                fields=["candidate", "-reviewed_at"],
                name="abx_indicat_candida_d1a427_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="indicationreview",
            index=models.Index(
                fields=["syndrome_decision"], name="abx_indicat_syndrom_5f91e9_idx"
            ),
        ),
    ]
