# Generated by Django 5.1.5 on 2026-02-08 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HAICandidate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hai_type",
                    models.CharField(
                        choices=[
                            ("clabsi", "Central Line-Associated BSI"),
                            ("ssi", "Surgical Site Infection"),
                            ("cauti", "Catheter-Associated UTI"),
                            ("vae", "Ventilator-Associated Event"),
                            ("cdi", "C. difficile Infection"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("patient_id", models.CharField(db_index=True, max_length=255)),
                ("patient_mrn", models.CharField(db_index=True, max_length=100)),
                (
                    "patient_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "patient_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("culture_id", models.CharField(max_length=255)),
                ("culture_date", models.DateTimeField()),
                ("organism", models.CharField(blank=True, default="", max_length=500)),
                ("device_info", models.JSONField(blank=True, null=True)),
                ("device_days_at_culture", models.IntegerField(blank=True, null=True)),
                ("meets_initial_criteria", models.BooleanField(default=True)),
                ("exclusion_reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Classification"),
                            ("classified", "Classified by LLM"),
                            ("pending_review", "Pending IP Review"),
                            ("confirmed", "Confirmed HAI"),
                            ("rejected", "Not HAI"),
                            ("excluded", "Excluded (Failed Criteria)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("type_specific_data", models.JSONField(blank=True, default=dict)),
                ("nhsn_reported", models.BooleanField(default=False)),
                ("nhsn_reported_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "HAI Candidate",
                "verbose_name_plural": "HAI Candidates",
                "db_table": "hai_candidates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["hai_type", "status"],
                        name="hai_candida_hai_typ_2e3fec_idx",
                    ),
                    models.Index(
                        fields=["patient_mrn", "-created_at"],
                        name="hai_candida_patient_f21123_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="hai_candida_status_f1e220_idx",
                    ),
                    models.Index(
                        fields=["culture_date"], name="hai_candida_culture_604b4c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hai_type", "culture_id"),
                        name="unique_hai_type_culture",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HAIClassification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("hai_confirmed", "HAI Confirmed"),
                            ("not_hai", "Not HAI"),
                            ("pending_review", "Needs IP Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField()),
                (
                    "alternative_source",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("is_mbi_lcbi", models.BooleanField(default=False)),
                ("supporting_evidence", models.JSONField(blank=True, default=list)),
                ("contradicting_evidence", models.JSONField(blank=True, default=list)),
                ("reasoning", models.TextField(blank=True, default="")),
                ("model_used", models.CharField(max_length=200)),
                ("prompt_version", models.CharField(max_length=50)),
                ("tokens_used", models.IntegerField(default=0)),
                ("processing_time_ms", models.IntegerField(default=0)),
                ("extraction_data", models.JSONField(blank=True, null=True)),
                ("rules_result", models.JSONField(blank=True, null=True)),
                (
                    "strictness_level",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="hai_detection.haicandidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "HAI Classification",
                "verbose_name_plural": "HAI Classifications",
                "db_table": "hai_classifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HAIReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "queue_type",
                    models.CharField(
                        choices=[
                            ("ip_review", "IP Review"),
                            ("manual_review", "Manual Review"),
                        ],
                        default="ip_review",
                        max_length=20,
                    ),
                ),
                ("reviewed", models.BooleanField(default=False)),
                ("reviewer", models.CharField(blank=True, default="", max_length=255)),
                (
                    "reviewer_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("confirmed", "Confirmed HAI"),
                            ("rejected", "Not HAI"),
                            ("needs_more_info", "Needs More Information"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True, default="")),
                (
                    "llm_decision",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_override", models.BooleanField(default=False)),
                ("override_reason", models.TextField(blank=True, default="")),
                (
                    "override_reason_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("extraction_error", "Extraction Error"),
                            ("rules_error", "Rules Engine Error"),
                            ("clinical_judgment", "Clinical Judgment"),
                            ("missing_documentation", "Missing Documentation"),
                            ("nhsn_interpretation", "NHSN Interpretation Difference"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("extraction_corrections", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="hai_detection.haicandidate",
                    ),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="hai_detection.haiclassification",
                    ),
                ),
            ],
            options={
                "verbose_name": "HAI Review",
                "verbose_name_plural": "HAI Reviews",
                "db_table": "hai_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=200)),
                ("success", models.BooleanField()),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("response_time_ms", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to="hai_detection.haicandidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Audit Log Entry",
                "verbose_name_plural": "LLM Audit Log Entries",
                "db_table": "hai_llm_audit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="haiclassification",
            index=models.Index(
                fields=["candidate", "-created_at"],
                name="hai_classif_candida_0bb313_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="haiclassification",
            index=models.Index(
                fields=["decision"], name="hai_classif_decisio_9a0133_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="haireview",
            index=models.Index(
                fields=["candidate", "-created_at"],
                name="hai_reviews_candida_7cc555_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="haireview",
            index=models.Index(
                fields=["reviewed", "-created_at"],
                name="hai_reviews_reviewe_ad2ad2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="haireview",
            index=models.Index(
                fields=["is_override"], name="hai_reviews_is_over_ca56b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="haireview",
            index=models.Index(
                fields=["queue_type", "reviewed"], name="hai_reviews_queue_t_cd3adc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmauditlog",
            index=models.Index(
                fields=["candidate", "-created_at"],
                name="hai_llm_aud_candida_49b2f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmauditlog",
            index=models.Index(fields=["model"], name="hai_llm_aud_model_8cfd1f_idx"),
        ),
    ]
